### ISSUE TITLE
Change ClientId upon CONNECT Request

### ISSUE THREAD

**Issue by drasko** [dergraf/vernemq_demo_plugin#2]
Is it possible to change ClientId, i.e. SubscriberId on CONNECT auth here: https://github.com/dergraf/vernemq_demo_plugin/blob/master/src/vernemq_demo_plugin.erl#L24

I would like to force ClientId to the value of UserName provided by the user to allow easier administration and integration with my system (user does not provide ClientId, only Username).

**Comment by dergraf** [comment]
Sure, you can override the SubscriberId by returning `{ok, [{subscriber_id, {Mountpoint, NewClientId}}]}` in auth_on_register.

**Comment by drasko** [comment]
What does `Mountpoint` represents here, and why here is a variable (capital `M`) and in code comment is an atom (lowercase `m`) -  https://github.com/dergraf/vernemq_demo_plugin/blob/master/src/vernemq_demo_plugin.erl#L32
